# Generated by Django 4.0.4 on 2022-05-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('author', models.CharField(max_length=30, verbose_name='Автор')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('content', models.CharField(max_length=255, verbose_name='Содержимое')),
            ],
        ),
    ]
